name: Build and Test Java App

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v2
      with:
        java-version: '11'
    - run: mvn install
    
  archive-artifact:
    runs-on: ubuntu-latest
    steps:
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.1
      with:
    # Artifact name
        name: shopping-cart-v2
    # A file, directory or wildcard pattern that describes what to upload
        path: target/*.jar
        retention-days: 2
    
   
